(setq data (list 
	(list "NIMBOSTRATUS" "PADA_DESZCZ" T "ZASLANIA_CALE_NIEBO" T )
	(list "CUMULONIMBUS" "PADA_DESZCZ" T "ZASLANIA_CALE_NIEBO" Nil )
	
	(list "CUMULUS" "PADA_DESZCZ" Nil "JEST_NISKO" T "ZASLANIA_CALE_NIEBO" Nil )
	(list "STRATUS" "PADA_DESZCZ" Nil "JEST_NISKO" T "ZASLANIA_CALE_NIEBO" T "JEST_ZWARTA" T )
	(list "STRATOCUMULUS" "PADA_DESZCZ" Nil "JEST_NISKO" T "ZASLANIA_CALE_NIEBO" T "JEST_ZWARTA" Nil )
	
	(list "ALTOSTRATUS" "PADA_DESZCZ" Nil "JEST_NISKO" Nil "JEST_GLADKA" T  "POKRYWA_WIEKSZOSC_NIEBA" T)
	(list "CIRROSTRATUS" "PADA_DESZCZ" Nil "JEST_NISKO" Nil "JEST_GLADKA" T  "POKRYWA_WIEKSZOSC_NIEBA" Nil "JEST_ZWARTA" T)
	(list "CIRRUS" "PADA_DESZCZ" Nil "JEST_NISKO" Nil "JEST_GLADKA" T  "POKRYWA_WIEKSZOSC_NIEBA" Nil "JEST_ZWARTA" Nil)
	
	(list "ALTOCUMULUS" "PADA_DESZCZ" Nil "JEST_NISKO" Nil "JEST_GLADKA" Nil "POKRYWA_WIEKSZOSC_NIEBA" T)
))
;;;(setq data (append data (list'(CIRROCUMULUS PADA_DESZCZ NIL JEST_NISKO NIL JEST_GLADKA NIL POKRYWA_WIEKSZOSC_NIEBA NIL))))