(setq data (list 
	(list "NIMBOSTRATUS" (list "PADA_DESZCZ" "ZASLANIA_CALE_NIEBO") (list) )
	(list "CUMULONIMBUS" '("PADA_DESZCZ") '("ZASLANIA_CALE_NIEBO") )
	
	(list "CUMULUS" (list "JEST_NISKO") (list "PADA_DESZCZ" "ZASLANIA_CALE_NIEBO") )
	(list "STRATUS" (list "JEST_NISKO" "ZASLANIA_CALE_NIEBO" "JEST_ZWARTA") (list "PADA_DESZCZ") )
	(list "STRATOCUMULUS" (list "JEST_NISKO" "ZASLANIA_CALE_NIEBO") (list "PADA_DESZCZ" "JEST_ZWARTA"))
	
	(list "ALTOSTRATUS" (list "JEST_GLADKA" "POKRYWA_WIEKSZOSC_NIEBA") (list "PADA_DESZCZ" "JEST_NISKO"))
	(list "CIRROSTRATUS" (list "JEST_GLADKA" "JEST_ZWARTA") (list "PADA_DESZCZ" "JEST_NISKO" "POKRYWA_WIEKSZOSC_NIEBA" ))
	(list "CIRRUS" (list  "JEST_GLADKA") (list "PADA_DESZCZ" "JEST_NISKO" "POKRYWA_WIEKSZOSC_NIEBA" "JEST_ZWARTA"))
	
	(list "ALTOCUMULUS" (list "POKRYWA_WIEKSZOSC_NIEBA") (list "PADA_DESZCZ" "JEST_NISKO" "JEST_GLADKA"))
))
;;;(setq data (append data (list'(CIRROCUMULUS PADA_DESZCZ NIL JEST_NISKO NIL JEST_GLADKA NIL POKRYWA_WIEKSZOSC_NIEBA NIL))))